# Generated by Django 3.1.1 on 2020-11-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gEvento', '0003_auto_20201011_2001'),
        ('gActividad', '0004_auto_20201012_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadPromocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gActividad.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividadesNecesarias', models.IntegerField()),
                ('precio', models.FloatField()),
                ('nombre', models.CharField(max_length=15)),
                ('visibilidad', models.BooleanField(default=True)),
                ('actividades', models.ManyToManyField(through='gPromocion.ActividadPromocion', to='gActividad.Actividad')),
                ('idEvento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gEvento.evento')),
            ],
        ),
        migrations.AddField(
            model_name='actividadpromocion',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gPromocion.promocion'),
        ),
    ]
