# Generated by Django 3.1.1 on 2020-11-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gPromocion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='actividades',
            new_name='actividadesP',
        ),
    ]
