# Generated by Django 3.1.1 on 2020-11-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gAmbiente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='descripcion',
            field=models.CharField(max_length=40),
        ),
    ]
