# Generated by Django 3.1.1 on 2020-11-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gAmbiente', '0002_auto_20201108_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='nombre',
            field=models.CharField(default='testambiente', max_length=40),
            preserve_default=False,
        ),
    ]
