# Generated by Django 3.1.1 on 2020-10-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fechaInicio', models.DateField()),
                ('fechaClausura', models.DateField()),
                ('ubicacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subevento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fechaInicio', models.DateField()),
                ('fechaClausura', models.DateField()),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gEvento.evento')),
            ],
        ),
    ]
