# Generated by Django 3.1.1 on 2020-10-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gEvento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='detalle',
            field=models.CharField(default='Asdas', max_length=50),
            preserve_default=False,
        ),
    ]
