# Generated by Django 3.1.1 on 2020-10-12 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gEvento', '0002_evento_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevento',
            name='idEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gEvento.evento'),
        ),
    ]
