# Generated by Django 3.1.1 on 2020-12-08 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextra',
            old_name='idSubevento',
            new_name='idUser',
        ),
    ]
