# Generated by Django 3.1.1 on 2020-12-10 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gEvento', '0003_auto_20201011_2001'),
        ('gMaterial', '0002_material_visibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaterialID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gEvento.evento')),
            ],
        ),
    ]
