# Generated by Django 3.1.1 on 2020-10-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gActividad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='horaFin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horaInicio',
            field=models.TimeField(),
        ),
    ]
