# Generated by Django 3.1.1 on 2020-10-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gActividad', '0002_auto_20201008_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(default='TEST1', max_length=30),
            preserve_default=False,
        ),
    ]
