# Generated by Django 3.1.1 on 2020-10-13 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gActividad', '0003_actividad_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponente',
            name='idActividad',
        ),
        migrations.CreateModel(
            name='ActividadPonente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gActividad.actividad')),
                ('ponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gActividad.ponente')),
            ],
        ),
        migrations.AddField(
            model_name='ponente',
            name='actividades',
            field=models.ManyToManyField(through='gActividad.ActividadPonente', to='gActividad.Actividad'),
        ),
    ]
