# Generated by Django 3.1.1 on 2020-11-11 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gEvento', '0003_auto_20201011_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=15, null=True)),
                ('url', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=45)),
                ('visibilidad', models.BooleanField(default=True)),
                ('idEvento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gEvento.evento')),
            ],
        ),
    ]
