# Generated by Django 3.1.1 on 2020-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gComite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='comite',
            name='url',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
