# Generated by Django 3.1.1 on 2020-11-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gComite', '0002_auto_20201111_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComitePersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gComite.comite')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('DNI', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=9)),
                ('correoElectronico', models.EmailField(max_length=45)),
                ('comites', models.ManyToManyField(through='gComite.ComitePersonal', to='gComite.Comite')),
            ],
        ),
        migrations.AddField(
            model_name='comitepersonal',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gComite.personal'),
        ),
    ]
